# https://github.com/jdrouet/docker-on-ci/blob/master/.travis.yml
# using aptman/qus instead of multiarch/qemu-user-static
# to load qemu binariesfor ppc64le emulation

dist: bionic

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled TARGET_ARCH=linux/amd64,linux/ppc64le

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - lsb_release -cs
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --rm --privileged aptman/qus -s -- -p ppc64le

before_script:
  - docker version
  - docker buildx create --name moc_builder --use

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker buildx build -t fnndsc/ubuntu-python3 --platform "$TARGET_ARCH" --progress plain --push .

after_script:
  - docker buildx rm
  - docker logout
